version: '3.8'

services:
  rabbitmq:
    container_name: erp_rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
  consumer:
    container_name: erp_processor
    build: .
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    networks:
      - network
    volumes:
      - .:/code
networks:
  network: {}
